name: lourdessantos
favicon: null
layout_spectrum: 0.19611
typography_spectrum: 0.04778
title: lourdes santos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171717'
    - '#767676'
    - '#9c9c9c'
    - '#555555'
    - '#d3d3d3'
  brandStrength: 0.0625
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
